version: '3.8'
services:
  db:
    container_name: postgreSQL
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: joro
      POSTGRES_PASSWORD: 34092109
      POSTGRES_DB: linkscribe
      DATABASE_HOST: postgreSQL
    ports:
      - "5433:5432"
    volumes:
      - postgresData:/var/lib/postgresql/data
  pgadmin:
    container_name: PGAdmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  backend:
    container_name: Backend_FastAPI
    image: backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:81"
  frontend:
    container_name: Frontend_ReactJS
    image: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  postgresData:
    driver: local